name: 'Setup Qt environment'
description: 'Setup Qt from their online installer'
author: 'Skycoder42'
inputs: 
  version:
    description: 'The Qt version to download and install. Example: 5.13.1'
    default: '5.13.1'
  platform:
    description: 'A version dependend platform package to be installed. Example: gcc_64'
    default: 'gcc_64'
  packages:
    description: 'A comma seperated list of additional packages to be installed per platform selected. Example: qtnetworkauth,qtwebengine'
    default: ''
  install-args:
    description: 'Extra arguments to be passed to the Qt maintenance installation'
    default: '--addRepository https://install.skycoder42.de/qtmodules/linux_x64'
runs:
  using: 'node12'
  main: 'lib/setup-qt.js'

