name: Test the action

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [gcc_64, msvc2017_64, clang_64]
        include: 
          - platform: gcc_64
            os: ubuntu-latest
            repo: linux_x64
          - platform: msvc2017_64
            os: windows-latest
            repo: windows_x86
          - platform: clang_64
            os: macos-latest
            repo: mac_x64

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/setup-python@v1.1.0
    - uses: Skycoder42/action-setup-qt@master
      with:
        version: 5.13.2
        platform: ${{matrix.platform}}
        packages: qtnetworkauth,qtwebengine
        install-args: "--addRepository https://install.skycoder42.de/qtmodules/${{matrix.repo}} --verbose"
    - name: "qmake stats"
      run: qmake -query
